image: node:lts
cache:
  paths:
    - node_modules/
pages:
  stage: deploy
  script:
    - npm install
    - CI=false NODE_OPTIONS=--max_old_space_size=4096 npm run build
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      - public
    expire_in: 30 days
  environment:
    name: production
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  variables:
    DISABLE_GZIP: "true"