image: node:lts
cache:
  paths:
    - node_modules/
pages:
  stage: deploy
  script:
    - npm install --legacy-peer-deps
    - CI=false NODE_OPTIONS=--max_old_space_size=4096 npm run build
    - cp build/index.html build/404.html
    - echo -e "/* /index.html 200\n/static/* /static/:splat 200" > build/_redirects
    - mv build public
    - ls -la public
    - ls -la public/static/js
    - ls -la public/static/css
    - ls -la public/static/media
    - cat public/index.html
  artifacts:
    paths:
      - public
    expire_in: 30 days
  environment:
    name: production
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  variables:
    DISABLE_GZIP: "true"