pages:
  stage: deploy
  script:
    - npm install --legacy-peer-deps
    - CI=false NODE_OPTIONS=--max_old_space_size=4096 npm run build
    - cp build/index.html build/404.html
    - echo -e "/* /index.html 200\n/static/* /static/:splat 200" > build/_redirects
    - mv build/* public/  # Move contents of build into public
    - mv build/.* public/ 2>/dev/null || true  # Move hidden files (e.g., .htaccess) if they exist, suppress errors
    - ls -la public/static/js || echo "Static JS directory not found, but proceeding anyway"  # Ignore failure if directory is missing
  artifacts:
    paths:
      - public
    expire_in: 30 days
  environment:
    name: production
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  variables:
    DISABLE_GZIP: "true"